version: '3.1'
services:

  app:
    container_name: ${PROJECT_NAME}-app
    extends:
      file: ./shared/dockerfiles/templates/frontend.yml
      service: apache
    depends_on:
      - mysql
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    build:
      args:
        service: frontend
        PROJECT_NAME: ${PROJECT_NAME}
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        PATH_SERVICES: ${PATH_SERVICES}
    volumes:
      - "../${PROJECT_NAME}-app:/var/www/html:rw"
    working_dir: /var/www/html
    command: >
      bash -c "./build-project.sh && /usr/sbin/apache2ctl -D FOREGROUND"

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}-de
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - ${PHPMA_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

  mongo:
    image: mongo
    container_name: ${PROJECT_NAME}-mongo
    restart: always
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: ${PROJECT_NAME}-mexp
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  maildev:
    image: djfarrelly/maildev
    container_name: ${PROJECT_NAME}-maildev
    ports:
      - ${MAILDEV_PORT}:80

volumes:
  mysql_data:
  mongo_data:
  rabbit:
    driver: local
  apache-logs:
    driver_opts:
      type: none
      device: ./apache-logs/
      o: bind
