version: '3'
services:

  app:
    container_name: ${PROJECT_NAME}-app
    extends:
      file: ./shared/dockerfiles/templates/common.yml
      service: apache
    depends_on:
      - mysql
    ports:
      - 83:80
    build:
      args:
        service: frontend
    volumes:
#      - "../hirefly-app:/var/www/html:rw"
      - type: volume
        source: "hirefly_app"
        target: "/var/www/html"
        read_only: false
    working_dir: /var/www/html
    command: >
      bash -c "composer install --prefer-dist -vvv --profile && yarn && yarn encore dev && /usr/sbin/apache2ctl -D FOREGROUND"

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hirefly-de
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    ports:
      - 8083:80
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

  maildev:
    image: djfarrelly/maildev
    container_name: ${PROJECT_NAME}-maildev
    ports:
      - 8002:80

volumes:
  hirefly_app:
    driver: local
    driver_opts:
      type: none
      device: ../hirefly-app
      o: bind
  mysql_data:
  mongo_data:
  rabbit:
    driver: local
  apache-logs:
    driver_opts:
      type: none
      device: ./apache-logs/
      o: bind
