---
#- name: Add PHP repo
#  apt_repository:
#    repo: ppa:ondrej/php

- name: Install PHP
  apt:
    name:
      - php7.4
      - php7.4-curl
      - php7.4-dev
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - php7.4-xmlrpc
      - php7.4-zip
      - php7.4-bcmath
      - libapache2-mod-php7.4
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Set PHP upload max filesize
  lineinfile: 
    dest: /etc/php/7.4/apache2/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 800M"
    state: present

- name: Set PHP post max filesize    
  lineinfile: 
    dest: /etc/php/7.4/apache2/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 800M"
    state: present