---
#- name: Add PHP repo
#  apt_repository:
#    repo: ppa:ondrej/php

- name: Install PHP
  apt:
    name:
      - php8.0
      - php8.0-curl
      - php8.0-dev
      - php8.0-gd
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-xml
      - php8.0-xmlrpc
      - php8.0-zip
      - php8.0-bcmath
      - libapache2-mod-php8.0
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Set PHP upload max filesize
  lineinfile: 
    dest: /etc/php/8.0/apache2/php.ini
    regexp: "^upload_max_filesize"
    line: "upload_max_filesize = 800M"
    state: present

- name: Set PHP post max filesize    
  lineinfile: 
    dest: /etc/php/8.0/apache2/php.ini
    regexp: "^post_max_size"
    line: "post_max_size = 800M"
    state: present