---
- name: Install php{{ PHP_VERSION }}-xdebug
  apt:
      name: php-xdebug
      state: present
      force: yes
      update_cache: yes

- name: Configure xdebug for PHP {{ PHP_VERSION }} in cli
  lineinfile:
      path: /etc/php/{{ PHP_VERSION }}/cli/php.ini
      line: '{{ item }}'
  with_items:
      - '[xdebug]'
      - 'xdebug.remote_autostart=1'
      - 'xdebug.remote_connect_back=1'
      - 'xdebug.remote_cookie_expire_time = 3600'
      - 'xdebug.remote_enable = 1'
      - 'xdebug.remote_host = localhost'
      - 'xdebug.remote_port = 9000'

- name: Configure xdebug for PHP {{ PHP_VERSION }} in apache2
  lineinfile:
      path: /etc/php/{{ PHP_VERSION }}/apache2/php.ini
      line: '{{ item }}'
  with_items:
      - '[xdebug]'
      - 'xdebug.remote_autostart=1'
      - 'xdebug.remote_connect_back=1'
      - 'xdebug.remote_cookie_expire_time = 3600'
      - 'xdebug.remote_enable = 1'
      - 'xdebug.remote_host = localhost'
      - 'xdebug.remote_port = 9000'